news/urls.py
from . import views
from django.urls import include, path
from django.contrib.auth.decorators import login_required
from .views import *
from .models import *



urlpatterns = [
    path('', NewsListView.as_view(), name='news'),
    path('add-news', NewsCreateView.as_view(), name='add_news'),
    path('detail-news/<slug:news_slug>/', NewsDetailView.as_view(), name='detail_news'),
    path("load-more-data-news", views.load_more_data_news, name='load_more_data_news'),
    path('edit_new/<int:pk>/', views.edit_new, name='edit_new'),
    path('new_delete/<int:pk>/', views.delete_new, name='new_delete'),
]

posts_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.sitemaps.views import sitemap
from posts.sitemaps import PostSitemap
from companies.sitemaps import CompanySitemap
from news.sitemaps import NewsSitemap

sitemaps = {
    'posts': PostSitemap,
    'company': CompanySitemap,
    'News': NewsSitemap
}

handler403 = 'posts.views.tr_handler403'
handler404 = 'posts.views.tr_handler404'
handler500 = 'posts.views.tr_handler500'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('companies/', include('companies.urls')),
    path('news/', include('news.urls')),
    path('', include('posts.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]  

posts/models.py
import datetime
from tabnanny import verbose
from tempfile import NamedTemporaryFile
from django.conf import settings
from django.core.files import File
from django.db import models
from django.shortcuts import render
from django.urls import reverse
import requests
import uuid
from django.contrib.auth.models import User
from slugify import slugify
from PIL import Image



class Post_sale(models.Model):
    class NewManager(models.Manager):
        def get_quertyser(self):
            return super().get_queryset().filter(published=True)

    type_object = models.ForeignKey('Type_object', on_delete=models.CASCADE, verbose_name='Тип объекта', default=0, blank=False, related_name='type_object_st')
    status = models.ForeignKey('Status', on_delete=models.CASCADE, verbose_name='Тип сделки', blank=False, default=0, related_name='status_st')
    adress = models.TextField(verbose_name='Адрес', max_length=1000, blank=True)
    body = models.TextField(verbose_name='Описание', max_length=5000)
    square = models.IntegerField(blank=True, null=True, verbose_name='Площадь дома')
    floors = models.IntegerField(verbose_name='Этажей в доме', blank=True, null=True)
    land_area = models.IntegerField(verbose_name='Площадь участка')
    land_status = models.ForeignKey('Land_status', on_delete=models.CASCADE, verbose_name='Статус земли', blank=True, null=True)
    heating = models.ForeignKey('Heating', on_delete=models.CASCADE, verbose_name='Отопление', blank=True, null=True)
    year_of_construction = models.CharField(verbose_name='Год постройки', max_length=4, blank=True, null=True)
    house_material = models.ForeignKey('House_material', on_delete=models.CASCADE, verbose_name='Материал Дома', null=True, blank=True)
    ceiling_height = models.CharField(verbose_name='Высота потолков', max_length=5, blank=True, null=True)
    water = models.ForeignKey('Water', on_delete=models.CASCADE, verbose_name='Водоснабжение', null=True, blank=True)
    price = models.IntegerField(verbose_name='Цена', null=True, blank=True)
    phone = models.CharField('Телефон', max_length=30, blank=True)
    created_at = models.DateTimeField (auto_now_add=True, verbose_name='Опубликовано')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор', related_name='user_post')
    published = models.BooleanField(verbose_name='Опубликован', default=True)
    views = models.IntegerField(default=0)
    houseAdditional = models.ManyToManyField('HouseAdditional', verbose_name='Благоустройство', blank=True)
    rent_amenities = models.ManyToManyField('Rent_amenities', verbose_name='Аренда удобства', blank=True)
    rent_price = models.CharField(verbose_name='Арендная плата', max_length=30, blank=True)
    rent_period = models.ForeignKey('RentPeriod', on_delete=models.CASCADE, verbose_name='Время аренды', blank=True, null=True, related_name='rent_period')
    favourites = models.ManyToManyField(User, related_name='favourite', default=None, blank=True)
    urgent_sales = models.BooleanField(verbose_name='Срочная продажа', default=False)
    district = models.ForeignKey('District', on_delete=models.CASCADE, verbose_name='Район', blank=True, null=True)
    objects = models.Manager()
    newmanager = NewManager ()

   
    def __str__(self):
        return self.body

    def get_absolute_url(self):
        return reverse('post_detail', kwargs={"pk": self.pk})

    @property
    def todaytime(self):
        current_date = datetime.date.today()
        date = self.created_at.date()
        if current_date == date:
            return True
        else:
            return False
    
    @property 
    def pub(self):
        current_date = datetime.date.today()
        date = self.created_at.date()
        date2 = date + datetime.timedelta(days=30)
        if current_date > date2:
            self.published = False
            self.save(self.published)
            return True

        else:
            return False
    class Meta :
        verbose_name = 'Объявление'
        verbose_name_plural = 'Объявления'
        
def images_directory_path(instance, filename):
    return '/'.join(['villages',str(instance.slug), str(uuid.uuid4().hex + ".png")])

class Cottvill(models.Model):
    title = models.TextField(max_length=200, unique=True, db_index=True, verbose_name='Название поселка', blank=True, null=True)
    slug = models.SlugField(max_length=50, unique=True, db_index=True, verbose_name='URL поселка')
    developer = models.TextField(max_length=100, verbose_name='Застройщик', blank=True, null=True)
    url = models.TextField(max_length=100 , verbose_name='Сайт поселка', blank=True, null=True)
    adress = models.TextField(max_length=800 , verbose_name='Адрес поселка', blank=True, null=True)
    status_land = models.ForeignKey('Land_status', on_delete=models.CASCADE, verbose_name='Статус земли', blank=True, null=True)
    col_area = models.IntegerField(verbose_name='Количество участков', blank=True, null=True)
    min_area = models.IntegerField(verbose_name='Минимальная площадь участка', blank=True, null=True)
    max_area = models.IntegerField(verbose_name='Максимальная площадь участка', blank=True, null=True)
    price_area = models.IntegerField(verbose_name='Цена участка', blank=True, null=True)
    сommunications = models.TextField(max_length=15 , verbose_name='Коммуникации', blank=True, null=True)
    body = models.TextField(max_length=9000 , verbose_name='Описание', blank=True, null=True)
    house_price_min = models.TextField(max_length=20 , verbose_name='Минимальная цена дома', blank=True, null=True)
    house_price_max = models.TextField(max_length=20 , verbose_name='Максимальная цена дома', blank=True, null=True)
    col_house = models.TextField(max_length=4 , verbose_name='Количество домов', blank=True, null=True)
    payment = models.TextField(max_length=20 , verbose_name='Ежемесячные взносы', blank=True, null=True)
    published = models.BooleanField(verbose_name='Опубликован', default=False)
    main_slider = models.BooleanField(verbose_name='На главном слайдере', default=False)
    img = models.ImageField(upload_to=images_directory_path, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор', related_name='user')


    def __str__(self):
        return self.title

    def save(self,  *args, **kwargs):
        self.slug = slugify(self.title)
        return super(Cottvill, self).save(*args, **kwargs)

    class Meta :
        verbose_name = 'Поселок'
        verbose_name_plural = 'Поселки'
    
    def get_absolute_url(self):
        return reverse('village_detail', kwargs={'village_slug': self.slug})
    
class Status(models.Model):
    title = models.TextField(max_length=50, db_index=True , verbose_name='Тип сделки', blank=True, null=True)
    slug = models.SlugField(max_length=50, unique=True, verbose_name='URL сделки')
       
    def __str__(self):
        return self.title
    class Meta :
        verbose_name = 'Тип сделки'
        verbose_name_plural = 'Типы сделки'

class RentPeriod (models.Model):
    title = models.TextField(max_length=50, db_index=True , verbose_name='Время аренды', blank=True, null=True)
    slug = models.SlugField(max_length=50, unique=True, verbose_name='URL время аренды')
       
    def __str__(self):
        return self.title
    class Meta :
        verbose_name = 'Время аренды'
        verbose_name_plural = 'Время аренды'        

class District(models.Model):
    title = models.TextField(max_length=50, db_index=True , verbose_name='Район объекта', blank=True, null=True)
    slug = models.SlugField(max_length=50, unique=True, verbose_name='URL района')
       
    def __str__(self):
        return self.title
    class Meta :
        verbose_name = 'Район объекта'
        verbose_name_plural = 'Районы объекта'

class Land_status(models.Model):
    title = models.TextField(max_length=50, db_index=True , verbose_name='Статус земли', blank=True, null=True)
       
    def __str__(self):
        return self.title

    class Meta :
        verbose_name = 'Статус земли'
        verbose_name_plural = 'Статусы земли'

class Heating(models.Model):
    title = models.TextField(max_length=50, db_index=True , verbose_name='Отопление', blank=True, null=True)
       
    def __str__(self):
        return self.title

    class Meta :
        verbose_name = 'Отопление'
        verbose_name_plural = 'Отопление'

class House_material(models.Model):
    title = models.TextField(max_length=50, db_index=True , verbose_name='Материал Дома')
       
    def __str__(self):
        return self.title
    
    class Meta :
        verbose_name = 'Материал Дома'
        verbose_name_plural = 'Материалы Дома'

class Type_object(models.Model):
    title = models.TextField(max_length=50, db_index=True , verbose_name='Тип объекта', blank=True, null=True)
    slug = models.SlugField(max_length=50, unique=True, verbose_name='URL объекта')
       
    def __str__(self):
        return self.title
    
    class Meta :
        verbose_name = 'Тип объекта'
        verbose_name_plural = 'Типы объекта'

class Rent_amenities(models.Model):
    title = models.TextField(max_length=50, db_index=True , verbose_name='Аренда удобства')
    slug = models.SlugField(max_length=50, unique=True, verbose_name='URL объекта')
       
    def __str__(self):
        return self.title
    
    class Meta :
        verbose_name = 'Аренда удобства'
        verbose_name_plural = 'Аренда удобства'


class HouseAdditional(models.Model):
    title = models.TextField(max_length=50, db_index=True , verbose_name='Благоустройство')
    slug = models.SlugField(max_length=50, unique=True, verbose_name='URL объекта')
       
    def __str__(self):
        return self.title
    
    class Meta :
        verbose_name = 'Благоустройство'
        verbose_name_plural = 'Благоустройства'

class Subscribers(models.Model):
    email = models.EmailField('',max_length=255, unique=True)

templates/create_profile.htm
{% block content %}
    {% if request.user.is_authenticated %}
        <div class="header-bar">
            <a href="{% url 'home' %}">&#8592; Back</a>
        </div>
    <div class="card-body">
        <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <input class="button" type="submit" value="Submit">
        </form>
    </div>
{% else %}
    <a href="{% url 'login' %}">Login</a>
{% endif %}

{% endblock content %}

templates/doma.html
{% extends 'base.html' %}
{% block title %}Объявления о продаже или аренде частного дома в Ленинградской области. Объектов в продаже: {{total_data}} - Zagorodoma.ru{% endblock %}
{% block description %}Широкий выбор частных домов в продаже или аренде на нашем сайте. Наш каталог включает в себя дома, коттеджи, земельные участки и таунхаусы. {% endblock %}
{% load static %}
{% block content %}
<div class="category-page-style">
<!--Подключение фильтра-->
{% include 'static/main_filter.html' %}
<!--Подключение фильтра-->
<!--Подключение карточки объекта-->
{% include 'static/card_posts.html' %}
<!--Подключение фильтра-->
</div>


<script src="{% static 'js/loadMoredoma.js' %}" type="text/javascript"></script>
<script src="{% static 'js/jscategory.js' %}" type="text/javascript"></script>
{% endblock content %}

templates/edit_post.html
{% extends 'base.html' %}

{% block content %}
{% if author.id == author.id %}
{% if user.is_authenticated %}
<div class="post-add-new-title"><h3 style="font-size: 20px;
  margin-bottom: 0 !important;
  margin-left: 10px;">Добавить объявление</h3></div>
<form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      
      <div class="form-floating">
      <!-- статус сделки-->
      <section class="card-add-post card-body border-0 shadow-sm p-4 mb-4" id="basic-info">
        <h2 class="h4 mb-4"><i class="fi fi-rr-briefcase"></i> Информация о сделке</h2>
        <div class="row">
          <div class="col-sm-6 mb-3">
            <label class="form-label" for="ap-category">Тип сделки <span class="text-danger">*</span></label>
            <ul id="id_status" class="payment-methods" style="padding-left: 0rem;">
            {% for radio in form.status %}
            {{ radio.tag }}
            <label for="{{ radio.id_for_label }}"> {{ radio.choice_label }} </label>
            {% endfor %}
            </ul>
          </div>
          <!-- статус сделки-->
          <div class="col-sm-6 mb-3">
            <label class="form-label" for="ap-type">Тип объекта <span class="text-danger">*</span></label>
            <ul id="id_type_object" class="payment-methods" style="padding-left: 0rem;">
            {% for radio in form.type_object %}
            {{ radio.tag }}
            <label for="{{ radio.id_for_label }}"> {{ radio.choice_label }} </label>
            {% endfor %}
            </ul>
            </div>
        </div>
      </section>
      <section class="card-add-post card-body border-0 shadow-sm p-4 mb-4" id="adress-info">
        <h2 class="h4 mb-4"><i class="fi-info-circle text-primary fs-5 mt-n1 me-2"></i> 
          <i class="fi fi-rr-marker"></i> Адрес</h2>
        <div class="row">
          <div class="form-floating col-sm-6 mb-3">
            {{ form.adress }} 
            <label for="id_adress" class="label-text-add-post">Адрес объекта</label>
          </div>
          <div class="form-floating col-sm-6 mb-3">
            {{ form.district }} <!-- адрес-->
            <label for="id_district" class="label-text-add-post">Район</label>
          </div>
        </div>
      </section>
      <section class="card-add-post card-body border-0 shadow-sm p-4 mb-4" id="object-info">
        <h2 class="h4 mb-4"><i class="fi fi-rr-list"></i>  Информация об объекте</h2>
        <div class="row">

          <div class="form-floating col-sm-6 mb-3">
            {{ form.land_area }} <!-- площадь участка-->
            <label for="id_land_area" class="label-text-add-post">Площадь участка, сот.</label>
          </div>


          <div class="form-floating col-sm-6 mb-3">
            {{ form.land_status }} <!-- статус земли-->
            <label for="id_land_status" class="label-text-add-post">Статус участка</label>
          </div>

          <div id="div_square" class="form-floating col-sm-6 mb-3">
            {{ form.square }} <!-- площадь дома-->
            <label for="id_square" class="label-text-add-post">Площадь дома, м²</label>
          </div>

          <div id="div_house_material" class="form-floating col-sm-6 mb-3">
            {{ form.house_material }} <!-- материал дома-->
            <label for="id_house_material" class="label-text-add-post">Материал дома</label>
          </div>

          <div id="div_year_of_construction" class="form-floating col-sm-6 mb-3">
            {{ form.year_of_construction }} <!-- год постройки-->
            <label for="id_year_of_construction" class="label-text-add-post">Год постройки</label>
          </div>

          <div id="div_floors" class="form-floating col-sm-6 mb-3">
            {{ form.floors }} <!-- этажей в дома-->
            <label for="id_floors" class="label-text-add-post">Кол-во этажей </label>
          </div>

          <div id="div_ceiling_height" class="form-floating ceiling_height col-sm-6 mb-3">
            {{ form.ceiling_height }} <!-- высота потолков-->
            <label for="id_ceiling_height" class="label-text-add-post">Высота потолков </label>
          </div>

          <div class="form-floating col-sm-6 mb-3">
            {{ form.water }} <!-- водоснабжение-->
            <label for="id_water" class="label-text-add-post">Водоснабжение</label>
          </div>

          <div class="form-floating col-sm-6 mb-3">
            {{ form.heating }} <!-- какое отопление в доме--> 
            <label for="id_heating" class="label-text-add-post">Отопление</label>
          </div>
          
          <div class="col-sm-6 mb-3">
            <label class="form-label" for="ap-type">Благоустройство <span class="text-danger">*</span></label>
            {{ form.houseAdditional }} <!-- Благоустройство-->
          </div>
          <div class="col-sm-6 mb-3">
            <label class="form-label" for="ap-type">Удобства <span class="text-danger">*</span></label>
            {{ form.rent_amenities }} <!-- удобвства аренды-->
          </div>
        </div>
      </section>
      <section class="card-add-post card-body border-0 shadow-sm p-4 mb-4" id="body-info">
        <h2 class="h4 mb-4"><i class="fi-info-circle text-primary fs-5 mt-n1 me-2"></i> 
          <i class="fi fi-rr-comment-alt"></i> Описание</h2>
        <div class="row">
          <div class="col-sm-10 mb-3">
            <label class="form-label" for="body-info">Описание <span class="text-danger">*</span></label>
            {{ form.body }} <!-- описание-->      
          </div>
        </div>
      </section>
      <section class="card-add-post card-body border-0 shadow-sm p-4 mb-4" id="photo-info">
        <h2 class="h4 mb-4"><i class="fi-info-circle text-primary fs-5 mt-n1 me-2"></i> 
          <i class="fi fi-rr-picture"></i> Фотографии </h2>
        <div class="row">
          <div class="col-sm-3 mb-3" style="width:100%;">
            <label class="form-label" for="photo-info">Фотографии <span class="text-danger">*</span>
              <div class="alert alert-warning" role="alert" style="width: 800px;">
                Для загрузки нескольких фотографий, их необходимо выделить при помощи ctrl!
              </div>

          </label>
          <div class="example-1">
            <div class="form-group">
              <label class="label">
                <i class="fi-rr-add-document"></i>
                <span class="title">Добавить фотографии</span>
                {{ form.all_images }}
              </label>
              {% for all_images in get_post.all_images.all %}
                  <img src="{{ all_images.image_data_link.url }}" class="rounded" style="width: 200px; height: 150px;"alt="продукт" >
                  {% endfor %}  
            </div>
            <div class="row">
              <span class="photo-add" id="output"></span>
          </div>
          </div>       
          </div>
        </div>
      </section>
      <section class="card-add-post card-body border-0 shadow-sm p-4 mb-4" id="price-info">
        <h2 class="h4 mb-4"><i class="fi-info-circle text-primary fs-5 mt-n1 me-2"></i> 
          <i class="fi fi-rr-coins"></i> Цена</h2>
        <div class="row">
          <div id="div_id_price" class="form-floating col-sm-4 mb-3">
            {{ form.price }}<!-- цена-->
            <label for="id_price" class="label-text-add-post">Цена, руб.</label>
          </div>
          <div class="col-sm-3 mb-3">
            <div class="form-check form-switch" > 
              {{ form.urgent_sales }} <label class="form-check-label" for="flexSwitchCheckDefault">Срочная продажа <img src="/media/static/flash-sale.png" width="20" height="20"></label>
            </div>        
          </div>
        </div>
      </section>
      <section class="card-add-post card-body border-0 shadow-sm p-4 mb-4" id="rent-info">
        <h2 class="h4 mb-4"><i class="fi-info-circle text-primary fs-5 mt-n1 me-2"></i> 
          <i class="fi fi-rr-coins"></i> Стоимость аренды</h2>
        <div class="row">
          <div id="div_id_rent_price" class="form-floating col-sm-4 mb-3">
            {{ form.rent_price }} <!-- стоимость аренды-->
            <label for="id_rent_price" class="label-text-add-post">Стоимость аренды, руб.</label>
          </div>
          <div class="col-sm-6 mb-3">
            <ul id="id_rent_period" class="payment-methods" style="padding-left: 0rem;">
            {% for radio in form.rent_period %}
            {{ radio.tag }}
            <label for="{{ radio.id_for_label }}"> {{ radio.choice_label }} </label>
            {% endfor %}
            </ul>
            </div>
        </div>
      </section>
      <section class="card-add-post card-body border-0 shadow-sm p-4 mb-4" id="phone-info">
        <h2 class="h4 mb-4"><i class="fi-info-circle text-primary fs-5 mt-n1 me-2"></i> 
          <i class="fi fi-rr-phone-call"></i> Телефон</h2>
        <div class="row">
          <div class="form-floating col-sm-4 mb-3">
            {{ form.phone }}  <!-- номер продавца-->
            <label for="id_phone" class="label-text-add-post">Мобильный телефон</label>
            
          </div>
        </div>
      </section>
    </div>
<input class="btn btn-success" style="margin: 0 auto;display: block;font-size: 19px;" type="submit" value="Разместить объявление" />
</form>

{% else %}
<button type="button" class="btn btn-outline-secondary" onclick="window.location.href = '{% url 'login' %}';">Войти</button>
{% endif %}
{% endif %}
<script>
  if(document.getElementById('id_status_1').checked) {
    $('#rent-info').show();
    $('#price-info').hide();
}else 
if(document.getElementById('id_status_0').checked) {
  $('#price-info').show();
  $('#rent-info').hide();
}


</script>
{% endblock content %}

templates/pagination.html
<ul class="pagination">
    {% if page_obj.has_previous %}
        {% if page_obj.number|add:'-3' > 1 %}
            <li class="page-item">
                <a class="page-link" href="?{{ status }}{{ type_object }}page=1">1</a>
            </li>
        {% endif %}
        {% if page_obj.number|add:'-3' >= 3 %}
            <li class="pagination__item pagination__item--dots">
                    <a href="?{{ status }}{{ type_object }}page={{ page_obj.previous_page_number|add:'-3' }}">
                <span class="page-link">• • •</span>
                </a>
            </li>
        {% endif %}
    {% endif %}
    {% if paginator.page_range|length > 1 %}
        {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="page-item active">
                    <a class="page-link" href="#">{{ i }}</a>
                </li>
            {% elif i > page_obj.number|add:'-4' and i < page_obj.number|add:'4' %}
                <li class="page-item">
                        <a class="page-link" href="?{{ status }}{{ type_object }}page={{ i }}">{{ i }}</a>
                </li>
            {% endif %}
        {% endfor %}
    {% endif %}
    {% if page_obj.has_next %}
        {% if page_obj.number|add:'4' < page_obj.paginator.num_pages %}
            <li class="pagination__item pagination__item--dots">
                    <a href="?{{ status }}{{ type_object }}page={{ page_obj.next_page_number|add:'3' }}">
                <span class="page-link">• • •</span>
                </a>
            </li>
        {% endif %}
        {% if page_obj.number|add:'3' < page_obj.paginator.num_pages %}
            <li class="page-item">
                    <a class="page-link" href="?{{ status }}{{ type_object }}page={{ page_obj.paginator.num_pages }}">
                        {{ page_obj.paginator.num_pages }}
                    </a>
            </li>
        {% endif %}
    {% endif %}
</ul>

templates/rent.html
{% extends 'base.html' %}
{% block title %}Объявления аренды недвижимости в Ленинградской области. Объектов в аренде: {{total_data}} - Zagorodoma.ru{% endblock %}
{% block description %}Широкий выбор объектов недвижимости в аренде на нашем сайте. Наш каталог включает в себя дома, коттеджи, земельные участки и таунхаусы. {% endblock %}
{% load static %}
{% block content %}
<div class="category-page-style">
<!--Подключение фильтра-->
{% include 'static/main_filter.html' %}
<!--Подключение фильтра-->
<!--Подключение карточки объекта-->
{% include 'static/card_posts.html' %}
<!--Подключение фильтра-->
</div>


<script src="{% static 'js/loadMorerent.js' %}" type="text/javascript"></script>
<script src="{% static 'js/jscategory.js' %}" type="text/javascript"></script>
{% endblock content %}

templates/signup.html
{% extends 'base.html' %}
{% block content %}
{% if request.user.is_authenticated %}
<div class="info-registration">
  <h4 class="alert-heading">Вы уже авторизованы. Вы не можете посетить эту страницу.</h4>
</div>
{% else %}
<!--{% if user_form.errors %}
<div class="alert alert-danger alert-dismissible fade show" role="alert" >
  {% for field in user_form %}
  {{ field.errors }}
  {% endfor %}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endif %}!-->
<main class="form-signin">
    <form method="post" action="{% url 'signup' %}" class="needs-validation">
      {% csrf_token %}
      <img class="mb-4" src="/media/static/logo-v2.png" alt="zagorodoma.ru" width="220" height="100" style="display: block;
      margin: 0 auto;">
      <h1 class="h3 mb-3 fw-normal">Регистрация</h1>
      <!--{{ field.errors }}!-->
      <div class="form-floating">
        <input type="text" class="form-control" id="id_username" placeholder="Логин" name="username" value="{{user_form.username.value|default_if_none:""}}" required> 
        <label for="id_username" class="label-text-add-post">Логин</label>
        <div class="error-reg">{{ user_form.errors.username }}</div>
      </div>
      <div class="form-floating">
        <input type="text" class="form-control" id="id_first_name" placeholder="Имя" name="first_name" value="{{user_form.first_name.value|default_if_none:""}}" required> 
        <label for="id_first_name" class="label-text-add-post">Имя</label>
      </div>
      <div class="form-floating">
        <input type="email" class="form-control" id="id_email" placeholder="email@mail.ru" name="email" value="{{user_form.email.value|default_if_none:""}}" required> 
        <label for="id_email" class="label-text-add-post">Почта</label>
        <div class="error-reg">{{ user_form.errors.email }}</div>
      </div>
      <div class="form-floating">
        <input type="password" class="form-control" id="id_password1" placeholder="Пароль" name="password" required>
        <label for="id_password1" class="label-text-add-post">Пароль</label>
        <div class="error-reg">{{ user_form.errors.password1 }}</div>
      </div>
      <div class="form-floating" style="margin-top: -5px;">
        <input type="password" class="form-control" id="id_password2" placeholder="Пароль" name="password2" required>
        <label for="id_password2" class="label-text-add-post">Подтверждение пароля</label>
        <div class="error-reg">{{ user_form.errors.password2 }}</div>
      </div>
      <button class="w-100 btn btn-lg btn-primary" type="submit">Зарегистрироваться</button>
      <a class="nav-link active" aria-current="page" href="{% url 'login' %}">Войти</a>
      <p class="mt-5 mb-3 text-muted">Загородома © 2017–2021</p>
    </form>
  </main>
  {% endif %}
  <script>
    (function () {
  'use strict'

  // Fetch all the forms we want to apply custom Bootstrap validation styles to
  var forms = document.querySelectorAll('.needs-validation')

  // Loop over them and prevent submission
  Array.prototype.slice.call(forms)
    .forEach(function (form) {
      form.addEventListener('submit', function (event) {
        if (!form.checkValidity()) {
          event.preventDefault()
          event.stopPropagation()
        }

        form.classList.add('was-validated')
      }, false)
    })
})()
  </script>
{% endblock content %}